### ISSUE TITLE
Rendering on iOS devices is poor

### ISSUE THREAD

**Issue by gurmukhp** [SpringRoll/PixiFlash#3]
Hi there

Thanks for building this prototype, it's amazing how much faster using Pixi is over EaselJS.

I've been playing around with exporting animations from Flash and viewing them on an iPad. Unfortunately, for some reason, the sprites show quite poorly on an iPad but on an Android they look fine? I've created two samples from the same source, do you know what could be the problem?

EaselJS - http://storage.googleapis.com/speed-test-web/elephant.html?a=1
PixiFlash - http://storage.googleapis.com/speed-test-web/elephant-single-pixi.html?a=1

![easel](https://cloud.githubusercontent.com/assets/899769/14388397/d3d4be0e-fda5-11e5-88c0-4c1a1d510c84.png)
![pixi](https://cloud.githubusercontent.com/assets/899769/14388398/d3d53c8a-fda5-11e5-8d3c-bddb7217da3c.png)

**Comment by bigtimebuddy** [comment]
Cool, thanks for sharing. Fun animation. 

I don't have an answer, but could you try something? Try putting a bitmap texture behind the PixiFlash version, and see if the edges still look chunky. I don't know if that will help, but I'm curious.

**Comment by andrewstart** [comment]
For the reasoning with the sprite behind the object, see https://github.com/pixijs/pixi.js/issues/1786 - iOS doesn't do real antialiasing, so the FXAA being used might not always work as nicely.

**Comment by andrewstart** [comment]
Also, I'd suggest using the `Copy Layers to Bitmap` JSFL script included in https://github.com/SpringRoll/FlashToolkit to convert your gradients to bitmaps quickly and easily.

**Comment by gurmukhp** [comment]
Thank you all for these insightful comments. Turning off anti aliasing definitely improved the rendering but it wasn't good enough. Adding a white background made it a **lot** better and usable especially once I resized the canvas by 50% to make it retina.
