### ISSUE TITLE
Question : Is it possible to run with gsap

### ISSUE THREAD

**Issue by yordan-kanchelov** [SpringRoll/PixiFlash#7]
Hey guys , I am wondering if its possible to run it with the [greensock animation platform](https://greensock.com/gsap) instead of tweenjs. I will try maybe tomorrow, but I was hoping for advice if you think its a bad idea and why.

**Comment by bigtimebuddy** [comment]
Hi @jkanchelov short answer is probably no. FYI, this project is not in active development so feel free to fork to fit your needs. We have abandoned it to implement a better publishing solution for Animate CC, which is yet to be released called PixiAnimate (https://github.com/jiborobot/pixi-animate). You might want to watch that project.

**Comment by yordan-kanchelov** [comment]
Thanks for the information. Me and my team are migrating to pixi from flash and currently looking for solutions if possible to keep the workflow as close as it can be as before. Could you share any info about the pixi-animate project about the progress and when to expect it. 

Thanks in advance.

**Comment by bigtimebuddy** [comment]
@jkanchelov [Email me](mailto:matt@mattkarl.com) and I can add you to the prerelease. We haven't fully supported Windows yet, Mac only.

**Comment by yordan-kanchelov** [comment]
Done. Thanks !
