### ISSUE TITLE
PIXI v4.5 renders all sprites to black

### ISSUE THREAD

**Issue by bdanis** [SpringRoll/PixiFlash#8]
running on the latest pixi (4.5.0) and all textures are rendered black.  Trying to poke around, but asking in case someone found a solution to this already.

If i create a new sprite, set a texture to the atlas loaded though, it displays properly. 

If i plug the new pixi on the examples, they all turn to black as well.

**Comment by bigtimebuddy** [comment]
FYI, this project is abandoned in favor of PixiAnimate:

* https://github.com/jiborobot/pixi-animate
* https://github.com/jiborobot/pixi-animate-extension

**Comment by bdanis** [comment]
Thanks a lot!
